matrix:
  RUST: [stable, beta, nightly]

steps:
  test:
    when:
      event: [push, pull_request]
      branch: main
      target: main
    image: rust
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $RUST
      - cargo check --all-targets -j 4
      - cargo test -j 4
